-- Placeholder for the IFS seed (DDL + INSERTs) generated by the Flutter
-- app. To populate Oracle on first start:
--
--   1. Open the Flutter app (flutter run -d chrome).
--   2. Source settings → "Copy seed SQL (DDL + INSERTs)".
--   3. Replace the contents of this file with what's on the clipboard.
--   4. From this directory: `docker compose down -v && docker compose up -d`.
--
-- The first time Oracle starts, this script runs as IFSAPP against the
-- IFSPRD pluggable database. Re-running `docker compose up` does NOT
-- re-execute init scripts — you must remove the `oracle_data` volume
-- (the `-v` flag on `down`) to trigger a re-init.

-- Sanity check so an empty placeholder doesn't fail the container.
SELECT 'IFS seed placeholder — populate via Flutter app' AS info FROM DUAL;
